events { worker_connections 1024; }

http {
    upstream mi_cluster_scalable {
        server web-app:80; # Docker resolverá esto automáticamente entre las réplicas
    }

    server {
        listen 80;
        location / {
            proxy_pass http://mi_cluster_scalable;
        }
    }
}