FROM ubuntu:22.04
RUN apt-get update && apt-get install -y openssh-server sudo
RUN mkdir /var/run/sshd

RUN useradd -rm -d /home/admin -s /bin/bash -g root -G sudo adminlab
RUN echo 'adminlab:password_temporal_blanqueada' | chpasswd

RUN mkdir -p /home/adminlab/.ssh && chmod 700 /home/adminlab/.ssh

COPY id_demo_ssh.pub /home/adminlab/.ssh/authorized_keys
RUN chmod 600 /home/adminlab/.ssh/authorized_keys && chown -R adminlab:root /home/adminlab/.ssh

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]
