---
- name: "Auditoria de Compliance en Minikube / K8s"
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    target_namespace: "audit-lab"
    audit_report_path: "./reporte-auditoria-k8s.txt"

  tasks:
    - name: "1. Obtener informacion de los Pods en el namespace objetivo"
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ target_namespace }}"
      register: pod_list

    - name: "2. Validar politicas de seguridad en Pods"
      set_fact:
        audit_results: >-
          [
          {% for pod in pod_list.resources %}
            {
              "name": "{{ pod.metadata.name }}",
              "image": "{{ pod.spec.containers[0].image }}",
              "status": "{{ pod.status.phase }}",
              "non_root_policy": "{% if pod.spec.containers[0].securityContext.runAsNonRoot | default(false) %}APROBADO{% else %}FALLIDO (Corre como root){% endif %}"
            }{% if not loop.last %},{% endif %}
          {% endfor %}
          ]

    - name: "3. Generar el reporte formal de auditoria"
      copy:
        content: |
          ==================================================
          REPORTE DE AUDITORIA Y COMPLIANCE - KUBERNETES
          ==================================================
          Fecha de ejecucion: {{ lookup('pipe', 'date "+%Y-%m-%d %H:%M:%S"') }}
          Cluster Context: Minikube Local
          Namespace Auditado: {{ target_namespace }}
          
          [ RECURSOS EVALUADOS ]:
          {% for item in (audit_results | from_json) %}
          - Pod: {{ item.name }}
            Imagen: {{ item.image }}
            Estado: {{ item.status }}
            Politica Non-Root: {{ item.non_root_policy }}
          {% endfor %}

          --------------------------------------------------
          DICTAMEN: EVALUACION COMPLETADA PARA AUDITORIA
          ==================================================
        dest: "{{ audit_report_path }}"

    - name: "4. Mostrar confirmacion en consola"
      debug:
        msg: "Auditoria finalizada. Se ha generado la evidencia en {{ audit_report_path }}"