[web_nginx]
nodo_nginx ansible_host=34.228.36.48 ansible_user=ubuntu ansible_ssh_private_key_file=./pem-lab-terraform.pem

[web_apache]
nodo_apache ansible_host=44.222.255.246 ansible_user=ubuntu ansible_ssh_private_key_file=./pem-lab-terraform.pem

[servidores_web:children]
web_nginx
web_apache

[servidores_web:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'