apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: labipap
spec:
  capacity: { storage: 1Gi }
  accessModes: [ReadWriteOnce]
  hostPath: { path: "/mnt/data-formatec" }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: labipap
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }