apiVersion: v1
kind: Service
metadata:
  name: servicio-interno
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: demo-networking # Apunta exactamente al label de nuestro Pod
