name: "Terraform AWS deploy"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform plan & apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./modulos/extras/repaso3

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./modulos/extras/repaso3

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ./modulos/extras/repaso3

      - name: Terraform apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        working-directory: ./modulos/extras/repaso3

      # Pausa de 2 minutos (120 segundos) para la demostración en vivo
      - name: Pausa para inspección en AWS (2 min)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: sleep 120

      - name: Terraform destroy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform destroy -auto-approve -input=false
        working-directory: ./modulos/extras/repaso3
