name: Hello-world-Ipap

on: push

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Hello-world-Ipap
        run: echo "Hello, wolrd"

      - name: touch file
        run: touch test.txt

      - name: set test.txt
        run: echo "Hola mundo" >> test.txt

      - name: show file
        run: cat -n test.txt

  otro:
    runs-on: ubuntu-latest
    steps:
      - name: LS
        run: ls -la
