name: Hello-world-Ipap

on:
  push:
    branches: ["integration"]
  pull_request:
    branches:
      - main

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Hello-world-Ipap
        run: echo "Hello, wolrd"

      - name: touch file
        run: touch test.txt

      - name: set test.txt
        run: echo "Hola mundo integration" >> test.txt

      - name: LS
        run: ls -la

      - name: show file
        run: cat -n test.txt

  otro:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: LS
        run: ls -la
