upstream backend_servers {
    server app-node-a:5000 max_fails=1 fail_timeout=2s;
    server app-node-b:5000 backup;
}

server {
    listen 80;
    location / {
        proxy_pass http://backend_servers;
        proxy_connect_timeout 1s;
        proxy_read_timeout 2s;
    }
}